version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - gem install chef-config -v '< 16.5.77'
      - gem install mixlib-log -v '~> 2'
      - gem install berkshelf -v '~> 5.1'
  build:
    commands:
      - echo Entered the build phase...
      - export REVISION_ID=`echo $REVISION | sed 's/\//-/g'`
      - berks package mh-opsworks-recipes-${REVISION_ID}.tar.gz
artifacts:
  files:
    - mh-opsworks-recipes-${REVISION_ID}.tar.gz
  discard-paths: yes

